services:
  eureka-server:
    build: 
      context: ./eureka-server/eureka-server
    image: eureka-server
    container_name: eureka-server
    ports: 
      - "8761:8761"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - smart-banking-platform_default

  api-gateway:
    build: 
      context: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports: 
      - "8086:8086"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8086/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s

    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-banking-platform_default

  auth-service:
    build: 
      context: ./auth-service
    image: auth-service
    container_name: auth-service
    ports: 
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - smart-banking-platform_default

  account-service:
    build: 
      context: ./account-service
    image: account-service
    container_name: account-service
    ports: 
      - "8082:8082"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    networks:
      - smart-banking-platform_default

  transaction-service:
    build: 
      context: ./transaction-service
    image: transaction-service
    container_name: transaction-service
    ports: 
      - "8083:8083"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8083/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      account-service:
        condition: service_healthy
    networks:
      - smart-banking-platform_default

  notification-service:
    build: 
      context: ./notification-service
    image: notification-service
    container_name: notification-service
    ports: 
      - "8085:8085"
    depends_on:
      eureka-server:
        condition: service_healthy
      transaction-service:
        condition: service_healthy
    networks:
      - smart-banking-platform_default

networks:
  smart-banking-platform_default:
    external: true